version: '3.9'

services:
  postgres:
    image: postgres:17.0-alpine3.20
    ports:
      - 5432:5432
    volumes:
      - ./etc/postgres/data:/var/lib/postgresql/data
      - ./etc/postgres/initdb:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    network_mode: host