version: '3.9'

services:
  postgres:
    image: postgres:17.0-alpine3.20
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ./etc/postgres/data:/var/lib/postgresql/data
      - ./etc/postgres/initdb/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password